# Permalinks
permalink:           pretty

# Setup
title:               Igor Felipe
# tagline:           
url:                 "https://iafelipe.github.io"
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Igor Felipe
  email:             igorafelipe@gmail.com
  # url:     

# Custom vars
version:             2.0.1
github:              iafelipe
linkedin:            igorafelipe

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist
